### ISSUE TITLE
不玩原神能用么

### ISSUE THREAD

**Issue by OtakuYuNine** [4ri1uvKiller/Kayiko#1]
如题

**Comment by 4ri1uvKiller** [comment]
可以，但是你需要下载崩坏星穹铁道并说帕姆可爱
![Uploading OIP.jpeg…]()

**Comment by 4ri1uvKiller** [comment]
可以，但是你需要下载崩坏星穹铁道并说帕姆可爱
![OIP](https://github.com/4ri1uvKiller/Kayiko/assets/137490940/c8e11692-c7ec-435d-a2fc-2f836ba23dc1)
